[pytest]
DJANGO_SETTINGS_MODULE = lovematch.settings
python_files = tests.py test_*.py *_tests.py
addopts = --nomigrations --reuse-db -v
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
