# Generated by Django 5.2.16 on 2026-07-23 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('interests', models.CharField(blank=True, default='', help_text='Comma-separated interests, e.g. hiking, cooking, music', max_length=500)),
                ('profile_pic', models.ImageField(blank=True, default='', upload_to='profile_pics/')),
                ('looking_for', models.CharField(choices=[('male', 'Men'), ('female', 'Women'), ('everyone', 'Everyone')], default='everyone', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
