# Generated by Django 6.1 on 2026-08-27 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or Bootstrap icon class', max_length=30)),
                ('category', models.CharField(default='General', max_length=30)),
            ],
            options={
                'verbose_name': 'Interest Tag',
                'verbose_name_plural': 'Interest Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_photos/')),
                ('caption', models.CharField(blank=True, default='', max_length=150)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfilePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('My ideal first date is...', 'My ideal first date is...'), ('A non-negotiable for me is...', 'A non-negotiable for me is...'), ('The most spontaneous thing I have done...', 'The most spontaneous thing I have done...'), ('Two truths and a lie...', 'Two truths and a lie...'), ('My favorite way to spend a rainy day...', 'My favorite way to spend a rainy day...'), ('I get way too excited about...', 'I get way too excited about...')], max_length=100)),
                ('answer', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('harassment', 'Harassment or Bullying'), ('inappropriate_content', 'Inappropriate Photos or Bio'), ('fake_profile', 'Fake Account or Impersonation'), ('spam', 'Spam or Commercial Solicitation'), ('other', 'Other Reason')], default='harassment', max_length=30)),
                ('description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed / Resolved'), ('action_taken', 'Action Taken (Warning/Ban)'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_incognito',
            field=models.BooleanField(default=False, help_text='Hide profile from public browse deck'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='zodiac_sign',
            field=models.CharField(blank=True, choices=[('Aries', 'Aries ♈'), ('Taurus', 'Taurus ♉'), ('Gemini', 'Gemini ♊'), ('Cancer', 'Cancer ♋'), ('Leo', 'Leo ♌'), ('Virgo', 'Virgo ♍'), ('Libra', 'Libra ♎'), ('Scorpio', 'Scorpio ♏'), ('Sagittarius', 'Sagittarius ♐'), ('Capricorn', 'Capricorn ♑'), ('Aquarius', 'Aquarius ♒'), ('Pisces', 'Pisces ♓')], default='Leo', max_length=20),
        ),
        migrations.CreateModel(
            name='BlockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_initiated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='interests_tags',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='accounts.interesttag'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['city'], name='accounts_pr_city_79ec1d_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender'], name='accounts_pr_gender_56b26b_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['looking_for'], name='accounts_pr_looking_54b3fb_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['birth_date'], name='accounts_pr_birth_d_002f13_idx'),
        ),
        migrations.AddField(
            model_name='profilephoto',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='profileprompt',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='reported_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='blockrecord',
            index=models.Index(fields=['blocker', 'blocked_user'], name='accounts_bl_blocker_be8b3f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blockrecord',
            unique_together={('blocker', 'blocked_user')},
        ),
        migrations.AlterUniqueTogether(
            name='profileprompt',
            unique_together={('profile', 'question')},
        ),
    ]
