# Generated by Django 6.1 on 2026-08-27 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Sunset Boba Walk, Arcade Night, Jazz Bar', max_length=150)),
                ('details', models.TextField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending Response'), ('accepted', 'Accepted 💖'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('suggested_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SwipeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('like', 'Like'), ('pass', 'Pass'), ('superlike', 'Super Like')], default='like', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='like',
            name='is_superlike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='match',
            name='unmatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='unmatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmatched_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['from_user', 'to_user'], name='matching_li_from_us_5c0bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user1', 'is_active'], name='matching_ma_user1_i_86296c_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user2', 'is_active'], name='matching_ma_user2_i_700385_idx'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['user', 'question'], name='matching_qu_user_id_5d9eb0_idx'),
        ),
        migrations.AddField(
            model_name='dateproposal',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_proposals', to='matching.match'),
        ),
        migrations.AddField(
            model_name='dateproposal',
            name='proposed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_proposals_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swipeaction',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swipeaction',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='swipeaction',
            index=models.Index(fields=['from_user', 'action'], name='matching_sw_from_us_18c840_idx'),
        ),
        migrations.AddIndex(
            model_name='swipeaction',
            index=models.Index(fields=['to_user', 'action'], name='matching_sw_to_user_ddce37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='swipeaction',
            unique_together={('from_user', 'to_user')},
        ),
    ]
